use_frameworks!

target 'CardanHome_Example' do
  pod 'CardanHome', :path => '../'

  target 'CardanHome_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
